import { SurveyAnswer } from "@/types/survey";

export const SAMPLE_ANSWERS: SurveyAnswer[] = [
  // KAWANISHI-2026 × 6
  {
    id: "sample-k1",
    participantId: "P-SAMPLE",
    macaronId: "KAWANISHI-2026",
    createdAt: "2025-10-01T10:00:00Z",
    answers: {
      sensedColor: { label: "ミントグリーン", hex: "#BEE8D4" },
      sensedShape: { label: "波", type: "wave" },
      memoryText: "川沿いの遊歩道、雨が上がって土の匂いが残っていた朝",
      intimacy: { label: "やや近い", value: 4 },
      urbanity: { label: "やや自然的", value: 2 },
      scentName: "雨上がりの河川敷",
    },
  },
  {
    id: "sample-k2",
    participantId: "P-SAMP2",
    macaronId: "KAWANISHI-2026",
    createdAt: "2025-10-01T11:00:00Z",
    answers: {
      sensedColor: { label: "セージグリーン", hex: "#A8BFA3" },
      sensedShape: { label: "層", type: "layer" },
      memoryText: "田んぼの脇の小道を自転車で走っていた夕方",
      intimacy: { label: "やや遠い", value: 2 },
      urbanity: { label: "とても自然的", value: 1 },
      scentName: "夕暮れの水路",
    },
  },
  {
    id: "sample-k3",
    participantId: "P-SAMP3",
    macaronId: "KAWANISHI-2026",
    createdAt: "2025-10-01T12:00:00Z",
    answers: {
      sensedColor: { label: "スカイブルー", hex: "#A7D8F0" },
      sensedShape: { label: "しずく", type: "drop" },
      memoryText: "洗濯物を取り込むとき、外の空気が家に入ってきた感覚",
      intimacy: { label: "とても近い", value: 5 },
      urbanity: { label: "どちらでもない", value: 3 },
      scentName: "洗濯物と外気",
    },
  },
  {
    id: "sample-k4",
    participantId: "P-SAMP4",
    macaronId: "KAWANISHI-2026",
    createdAt: "2025-10-01T13:00:00Z",
    answers: {
      sensedColor: { label: "グレージュ", hex: "#C9BFB3" },
      sensedShape: { label: "雲", type: "cloud" },
      memoryText: "川の上流、石が重なる場所で昼寝をしていた記憶",
      intimacy: { label: "どちらでもない", value: 3 },
      urbanity: { label: "とても自然的", value: 1 },
      scentName: "石と水の昼寝場所",
    },
  },
  {
    id: "sample-k5",
    participantId: "P-SAMP5",
    macaronId: "KAWANISHI-2026",
    createdAt: "2025-10-01T14:00:00Z",
    answers: {
      sensedColor: { label: "アプリコット", hex: "#F4B183" },
      sensedShape: { label: "渦", type: "spiral" },
      memoryText: "子供のころ、近所の用水路で遊んだ夏の日の匂い",
      intimacy: { label: "とても遠い", value: 1 },
      urbanity: { label: "やや自然的", value: 2 },
      scentName: "用水路の夏",
    },
  },
  {
    id: "sample-k6",
    participantId: "P-SAMP6",
    macaronId: "KAWANISHI-2026",
    createdAt: "2025-10-01T15:00:00Z",
    answers: {
      sensedColor: { label: "ペールピンク", hex: "#F7C8D0" },
      sensedShape: { label: "花", type: "flower" },
      memoryText: "土手に咲いていた花の匂いが風に運ばれてきた春の朝",
      intimacy: { label: "やや近い", value: 4 },
      urbanity: { label: "やや自然的", value: 2 },
      scentName: "土手の春風",
    },
  },
  // TAKARAZUKA-1887 × 6
  {
    id: "sample-t1",
    participantId: "P-SAMPLE",
    macaronId: "TAKARAZUKA-1887",
    createdAt: "2025-10-02T10:00:00Z",
    answers: {
      sensedColor: { label: "ラベンダー", hex: "#C9B6E4" },
      sensedShape: { label: "円", type: "circle" },
      memoryText: "古い洋館の庭、誰もいない午後に石畳を歩いていた",
      intimacy: { label: "やや遠い", value: 2 },
      urbanity: { label: "やや自然的", value: 2 },
      scentName: "無人の庭園",
    },
  },
  {
    id: "sample-t2",
    participantId: "P-SAMP2",
    macaronId: "TAKARAZUKA-1887",
    createdAt: "2025-10-02T11:00:00Z",
    answers: {
      sensedColor: { label: "モーヴ", hex: "#B58AA5" },
      sensedShape: { label: "楕円", type: "oval" },
      memoryText: "祖母が育てていたハーブが窓辺に並んでいた部屋",
      intimacy: { label: "とても遠い", value: 1 },
      urbanity: { label: "とても自然的", value: 1 },
      scentName: "祖母のハーブ棚",
    },
  },
  {
    id: "sample-t3",
    participantId: "P-SAMP3",
    macaronId: "TAKARAZUKA-1887",
    createdAt: "2025-10-02T12:00:00Z",
    answers: {
      sensedColor: { label: "ミルクホワイト", hex: "#FFF8EE" },
      sensedShape: { label: "粒", type: "grain" },
      memoryText: "美術館の庭にいたとき、時間が静止したような空気感",
      intimacy: { label: "どちらでもない", value: 3 },
      urbanity: { label: "どちらでもない", value: 3 },
      scentName: "静止した美術館の外",
    },
  },
  {
    id: "sample-t4",
    participantId: "P-SAMP4",
    macaronId: "TAKARAZUKA-1887",
    createdAt: "2025-10-02T13:00:00Z",
    answers: {
      sensedColor: { label: "セージグリーン", hex: "#A8BFA3" },
      sensedShape: { label: "線", type: "line" },
      memoryText: "庭木の手入れをしている老人の傍らに立っていた昼下がり",
      intimacy: { label: "やや遠い", value: 2 },
      urbanity: { label: "やや自然的", value: 2 },
      scentName: "剪定された午後",
    },
  },
  {
    id: "sample-t5",
    participantId: "P-SAMP5",
    macaronId: "TAKARAZUKA-1887",
    createdAt: "2025-10-02T14:00:00Z",
    answers: {
      sensedColor: { label: "ペールピンク", hex: "#F7C8D0" },
      sensedShape: { label: "花", type: "flower" },
      memoryText: "演劇の幕間、ロビーに漂っていた何かの芳香剤の記憶",
      intimacy: { label: "とても遠い", value: 1 },
      urbanity: { label: "やや都市的", value: 4 },
      scentName: "幕間のロビー",
    },
  },
  {
    id: "sample-t6",
    participantId: "P-SAMP6",
    macaronId: "TAKARAZUKA-1887",
    createdAt: "2025-10-02T15:00:00Z",
    answers: {
      sensedColor: { label: "グレージュ", hex: "#C9BFB3" },
      sensedShape: { label: "雲", type: "cloud" },
      memoryText: "廃墟になった洋館を見学した日、朽ちた木とガラスの匂い",
      intimacy: { label: "どちらでもない", value: 3 },
      urbanity: { label: "どちらでもない", value: 3 },
      scentName: "廃館の記憶",
    },
  },
  // UMEDA-BC4000 × 6
  {
    id: "sample-u1",
    participantId: "P-SAMPLE",
    macaronId: "UMEDA-BC4000",
    createdAt: "2025-10-03T10:00:00Z",
    answers: {
      sensedColor: { label: "チャコール", hex: "#4B4B4B" },
      sensedShape: { label: "角", type: "angle" },
      memoryText: "地下鉄の改札を出たとき、換気扇と人の体温が混ざった空気",
      intimacy: { label: "とても近い", value: 5 },
      urbanity: { label: "とても都市的", value: 5 },
      scentName: "地下駅の体温",
    },
  },
  {
    id: "sample-u2",
    participantId: "P-SAMP2",
    macaronId: "UMEDA-BC4000",
    createdAt: "2025-10-03T11:00:00Z",
    answers: {
      sensedColor: { label: "キャラメルブラウン", hex: "#B9835A" },
      sensedShape: { label: "断片", type: "fragment" },
      memoryText: "深夜のビルの地下駐車場、排気ガスとコンクリートの冷たさ",
      intimacy: { label: "やや近い", value: 4 },
      urbanity: { label: "とても都市的", value: 5 },
      scentName: "深夜の地下駐車場",
    },
  },
  {
    id: "sample-u3",
    participantId: "P-SAMP3",
    macaronId: "UMEDA-BC4000",
    createdAt: "2025-10-03T12:00:00Z",
    answers: {
      sensedColor: { label: "グレージュ", hex: "#C9BFB3" },
      sensedShape: { label: "層", type: "layer" },
      memoryText: "百貨店の地下食料品売り場を通り過ぎるとき、香り同士が重なる感覚",
      intimacy: { label: "どちらでもない", value: 3 },
      urbanity: { label: "やや都市的", value: 4 },
      scentName: "地下食品売り場の重なり",
    },
  },
  {
    id: "sample-u4",
    participantId: "P-SAMP4",
    macaronId: "UMEDA-BC4000",
    createdAt: "2025-10-03T13:00:00Z",
    answers: {
      sensedColor: { label: "アプリコット", hex: "#F4B183" },
      sensedShape: { label: "渦", type: "spiral" },
      memoryText: "終電を逃した夜、一人で歩いた繁華街の路地",
      intimacy: { label: "やや近い", value: 4 },
      urbanity: { label: "とても都市的", value: 5 },
      scentName: "終電後の路地",
    },
  },
  {
    id: "sample-u5",
    participantId: "P-SAMP5",
    macaronId: "UMEDA-BC4000",
    createdAt: "2025-10-03T14:00:00Z",
    answers: {
      sensedColor: { label: "レモンイエロー", hex: "#F8E88B" },
      sensedShape: { label: "粒", type: "grain" },
      memoryText: "工事現場の近くを通ったとき、コンクリートと鉄の匂いに混じった微かな甘み",
      intimacy: { label: "やや遠い", value: 2 },
      urbanity: { label: "やや都市的", value: 4 },
      scentName: "工事現場の甘み",
    },
  },
  {
    id: "sample-u6",
    participantId: "P-SAMP6",
    macaronId: "UMEDA-BC4000",
    createdAt: "2025-10-03T15:00:00Z",
    answers: {
      sensedColor: { label: "スカイブルー", hex: "#A7D8F0" },
      sensedShape: { label: "線", type: "line" },
      memoryText: "地下街の出口から地上へ出た瞬間、急に冷たい外気が触れた感覚",
      intimacy: { label: "どちらでもない", value: 3 },
      urbanity: { label: "やや都市的", value: 4 },
      scentName: "地上への出口",
    },
  },
];
